#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testuje
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database_Trial")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTrial_Table(Trial_Table instance);
    partial void UpdateTrial_Table(Trial_Table instance);
    partial void DeleteTrial_Table(Trial_Table instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Testuje.Properties.Settings.Default.Database_TrialConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Trial_Table> Trial_Table
		{
			get
			{
				return this.GetTable<Trial_Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trial_Table")]
	public partial class Trial_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nazwa_eksportu;
		
		private System.DateTime _data_wprowadzenia;
		
		private string _uzytkownik;
		
		private string _lokal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnazwa_eksportuChanging(string value);
    partial void Onnazwa_eksportuChanged();
    partial void Ondata_wprowadzeniaChanging(System.DateTime value);
    partial void Ondata_wprowadzeniaChanged();
    partial void OnuzytkownikChanging(string value);
    partial void OnuzytkownikChanged();
    partial void OnlokalChanging(string value);
    partial void OnlokalChanged();
    #endregion
		
		public Trial_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa_eksportu", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string nazwa_eksportu
		{
			get
			{
				return this._nazwa_eksportu;
			}
			set
			{
				if ((this._nazwa_eksportu != value))
				{
					this.Onnazwa_eksportuChanging(value);
					this.SendPropertyChanging();
					this._nazwa_eksportu = value;
					this.SendPropertyChanged("nazwa_eksportu");
					this.Onnazwa_eksportuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_wprowadzenia", DbType="DateTime2 NOT NULL")]
		public System.DateTime data_wprowadzenia
		{
			get
			{
				return this._data_wprowadzenia;
			}
			set
			{
				if ((this._data_wprowadzenia != value))
				{
					this.Ondata_wprowadzeniaChanging(value);
					this.SendPropertyChanging();
					this._data_wprowadzenia = value;
					this.SendPropertyChanged("data_wprowadzenia");
					this.Ondata_wprowadzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uzytkownik", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string uzytkownik
		{
			get
			{
				return this._uzytkownik;
			}
			set
			{
				if ((this._uzytkownik != value))
				{
					this.OnuzytkownikChanging(value);
					this.SendPropertyChanging();
					this._uzytkownik = value;
					this.SendPropertyChanged("uzytkownik");
					this.OnuzytkownikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lokal", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string lokal
		{
			get
			{
				return this._lokal;
			}
			set
			{
				if ((this._lokal != value))
				{
					this.OnlokalChanging(value);
					this.SendPropertyChanging();
					this._lokal = value;
					this.SendPropertyChanged("lokal");
					this.OnlokalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
